version: '3.5'

services:
  ocsen-auj:
    image: ocsen-auj:latest
    container_name: ocsen-auj
    restart: unless-stopped
    # volumes: 
    #   - ".:/usr/src/app"
    ports:
      - 8888:8888
    networks:
      - ocsen-network

#   postgres:
#     image: postgres:latest
#     container_name: postgres
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: ocsen-db
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: root
#     ports:
#       - 5432:5432
#     volumes: 
#       - ./pg-data:/var/lib/postgresql/data
#     networks:
#       - ocsen-network

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin
#     restart: unless-stopped
#     ports:
#       - 8080:80
#     environment:
#       PGADMIN_DEFAULT_EMAIL: root@admin.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     depends_on:
#       - postgres
#     networks:
#       - ocsen-network

# volumes:
#   pg-data:
#     driver: local

networks:
  ocsen-network:
    driver: bridge  